name = "SketchySVD"
uuid = "63952964-c1bf-46db-9b02-50148abd88ef"
authors = ["smallpondtom <tkoike45@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extras]
MKLSparse = "0c723cd3-b8cd-5d40-b370-ba682dde9aae"

[compat]
FFTW = "1.10.0"
LinearAlgebra = "1.11.0, 1.12.0"
MKLSparse = "3.0.0"
ProgressMeter = "1.11.0"
Random = "1.11.0"
SparseArrays = "1.11.0, 1.12.0"
StatsBase = "0.34, 0.35"
julia = "1.11"